// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdkhhnnhvnghztkjnfvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impka2hobm5odm5naHp0a2puZnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDAxODAsImV4cCI6MjA3MzAxNjE4MH0.5Z8D2-zQMswVxmWhBYadOaTZM4tTPif8KiXeiEVON_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});